/** @type {import("prettier").Config} */
const config = {
  arrowParens: "always",
  printWidth: 80,
  singleQuote: false,
  jsxSingleQuote: false,
  semi: true,
  trailingComma: "all",
  tabWidth: 2,
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
  pluginSearchDirs: false,
  tailwindConfig: "./packages/quickcheck-shared/tailwind.config.ts",
  importOrder: [
    "^(react(.*)/(.*)$)|^(react(.*)$)",
    "^(@remix-run/(.*)$)|^(@remix-run$)",
    "",
    "<THIRD_PARTY_MODULES>",
    "",
    "^(quickcheck-shared/(.*)$)|^(quickcheck-shared$)",
    "",
    "^~/contentstack/(.*)$|^~/contentstack$",
    "^~/graphql/(.*)$|^~/graphql",
    "",
    "^~/utils/(.*)$",
    "",
    "^~/models/(.*)$|^~/mocks/(.*)$",
    "",
    "^~/pages/(.*)$|^~/pages",
    "",
    "^~/components/(.*)$|^~/components$",
    "",
    "^./utils/(.*)$",
    "",
    "^./models/(.*)$|^./mocks/(.*)$",
    "",
    "^./components/(.*)$|^./components$",
    "",
    "^./hooks/(.*)$",
    "",
    "^./handlers/(.*)$|^./handlers$",
    "^./actions/(.*)$|^./actions$",
    "",
    "^[./]",
  ],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderTypeScriptVersion: "4.9.5",
};

module.exports = config;
