import type { QuestionItem, Taxon, UserData } from "quickcheck-shared";

import { QuickcheckQuestionEmail } from "../templates/QuickcheckQuestionEmail";
import { i18n } from "../utils/i18n";

const QuickcheckQuestionEmailPreview = () => {
  const t = i18n.getFixedT("en-us");
  return (
    <QuickcheckQuestionEmail
      userData={userData}
      questionItem={questionItemMock}
      enrollmentTaxonomy={enrollmentTaxonomyMock}
      t={t}
      loginUrl="https://example.com/token/TOKEN"
      questionId="questionId"
    />
  );
};

export default QuickcheckQuestionEmailPreview;

const userData: UserData = {
  unanswered_questions: 24,
  active_enrollments: 3,
};

const enrollmentTaxonomyMock = {
  _version: 1,
  locale: "en-us",
  uid: "blt592c5251c4d441a1",
  ACL: {},
  _in_progress: false,
  created_at: "2023-07-26T19:08:22.448Z",
  created_by: "blt97eeb68c0ab9afcf",
  display_name: "Sprint Selling",
  parent_taxonomy: [],
  tags: ["ss"],
  title: "Sprint Selling",
  updated_at: "2023-07-26T19:08:22.448Z",
  updated_by: "blt97eeb68c0ab9afcf",
  publish_details: {
    environment: "blt1e7485ffdf16a13e",
    locale: "en-us",
    time: "2023-07-26T19:51:44.477Z",
    user: "blt97eeb68c0ab9afcf",
  },
  content_type: {
    title: "Taxonomy",
    description: "",
    options: {
      is_page: false,
      singleton: false,
      sub_title: [],
      title: "title",
    },
    schema: [
      {
        data_type: "text",
        display_name: "Title",
        field_metadata: { _default: true, version: 3 },
        mandatory: true,
        uid: "title",
        unique: true,
        multiple: false,
        non_localizable: false,
      },
      {
        data_type: "text",
        display_name: "Display Name",
        uid: "display_name",
        field_metadata: { description: "", default_value: "", version: 3 },
        format: "",
        error_messages: { format: "" },
        mandatory: true,
        multiple: false,
        non_localizable: false,
        unique: false,
      },
      {
        data_type: "reference",
        display_name: "Parent Taxonomy",
        reference_to: ["taxon_bottom_up"],
        field_metadata: {
          ref_multiple: false,
          ref_multiple_content_types: true,
        },
        uid: "parent_taxonomy",
        mandatory: false,
        multiple: false,
        non_localizable: false,
        unique: false,
      },
    ],
    uid: "taxon_bottom_up",
    DEFAULT_ACL: { others: { read: false, create: false }, users: [] },
    SYS_ACL: {
      others: {
        read: false,
        create: false,
        update: false,
        delete: false,
        sub_acl: {
          read: false,
          create: false,
          update: false,
          delete: false,
          publish: false,
        },
      },
      roles: [],
    },
    created_at: "2023-06-21T20:04:24.985Z",
    updated_at: "2023-07-19T19:28:33.298Z",
    inbuilt_class: false,
    abilities: {
      get_one_object: true,
      get_all_objects: true,
      create_object: true,
      update_object: true,
      delete_object: true,
      delete_all_objects: true,
    },
    last_activity: {},
    maintain_revisions: true,
    _version: 8,
  },
} as Taxon;

const questionItemMock = {
  _version: 3,
  locale: "en-us",
  uid: "blt49e020c2eb8d77c3",
  ACL: {},
  _in_progress: false,
  client_list: null,
  created_at: "2023-07-27T14:54:56.329Z",
  created_by: "blt97eeb68c0ab9afcf",
  tags: ["manage plan", "ss4"],
  title: "SS4 Manage Plan - Manage the Collaboration Plan",
  topic: [
    {
      _content_type_uid: "taxon_bottom_up",
      title: "Manage Plan SS4",
      display_name: "Manage Plan",
      parent_taxonomy: [
        {
          _content_type_uid: "taxon_bottom_up",
          _version: 1,
          locale: "en-us",
          uid: "blt592c5251c4d441a1",
          ACL: {},
          _in_progress: false,
          created_at: "2023-07-26T19:08:22.448Z",
          created_by: "blt97eeb68c0ab9afcf",
          display_name: "Sprint Selling",
          parent_taxonomy: [],
          tags: ["ss"],
          title: "Sprint Selling",
          updated_at: "2023-07-26T19:08:22.448Z",
          updated_by: "blt97eeb68c0ab9afcf",
          publish_details: {
            environment: "blt1e7485ffdf16a13e",
            locale: "en-us",
            time: "2023-07-26T19:51:44.477Z",
            user: "blt97eeb68c0ab9afcf",
          },
        },
      ],
      tags: ["ss4"],
      locale: "en-us",
      uid: "blt16a49dfe30f67e45",
      created_by: "blt97eeb68c0ab9afcf",
      updated_by: "blt64a28744b71eb0d2",
      created_at: "2023-07-27T14:55:19.711Z",
      updated_at: "2023-08-01T19:18:17.088Z",
      ACL: {},
      _version: 2,
      _in_progress: false,
      publish_details: {
        environment: "blt1e7485ffdf16a13e",
        locale: "en-us",
        time: "2023-08-01T19:44:24.539Z",
        user: "blt64a28744b71eb0d2",
      },
    } as Taxon,
  ],
  updated_at: "2023-08-01T19:28:41.142Z",
  updated_by: "blt64a28744b71eb0d2",
  variants: [
    {
      mcquestion: {
        prompt: "",
        _metadata: { uid: "csf1cb57577985188c" },
        // video_file: null,
        // video_caption_file: null,
        stem: "<span>You have cocreated a Collaboration Plan with Power and are now using it to manage the sale. Which of the following best practices is specific to managing the Collaboration Plan?</span>",
        instruction: "",
        choices: [
          {
            choice: {
              correct: true,
              _metadata: { uid: "cs98512e70be208a33" },
              points: null,
              body: "<span>Anchor all key customer meetings to the events in the Collaboration Plan.</span>",
              feedback:
                "<span>It is best practice when executing the plan to refer to it as you open and close all key customer meetings.</span>",
            },
          },
          {
            choice: {
              correct: false,
              _metadata: { uid: "cs9c2b22deb977ff23" },
              points: null,
              body: "<span>Do research on key stakeholders with whom you have upcoming meetings based on the Collaboration Plan.</span>",
              feedback:
                "<span>This option is not specific to managing the Collaboration Plan. It is a general best practice for preparing for any stakeholder meeting.</span>",
            },
          },
          {
            choice: {
              correct: false,
              _metadata: { uid: "cs135d9f410005ceb5" },
              points: null,
              body: "<span>Score your Opportunity Health after each key customer interaction noted in the Collaboration Plan.</span>",
              feedback:
                "<span>This option is not specific to managing the Collaboration Plan. It is a general best practice for the Advance phase of a Selling Sprint, before and after you have a Collaboration Plan in place.</span>",
            },
          },
          {
            choice: {
              correct: false,
              _metadata: { uid: "cs28d8c78969209fcf" },
              points: null,
              body: "<span>Brainstorm events to include in the plan with Power.</span>",
              feedback:
                "<span>This option is a best practice for cocreating the plan, which happens before you execute it.</span>",
            },
          },
        ],
      },
    },
  ],
  publish_details: {
    environment: "blt1e7485ffdf16a13e",
    locale: "en-us",
    time: "2023-08-01T19:44:24.724Z",
    user: "blt64a28744b71eb0d2",
  },
  content_type: {
    title: "QuestionItem",
    description: "",
    options: {
      is_page: false,
      singleton: false,
      sub_title: [],
      title: "title",
    },
    schema: [
      {
        data_type: "text",
        display_name: "Title",
        field_metadata: { _default: true, version: 3 },
        mandatory: true,
        uid: "title",
        unique: true,
        multiple: false,
        non_localizable: false,
      },
      {
        data_type: "blocks",
        display_name: "Variants",
        blocks: [
          {
            title: "MCQuestion",
            uid: "mcquestion",
            schema: [
              {
                data_type: "text",
                display_name: "Prompt",
                uid: "prompt",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "file",
                display_name: "Video File",
                uid: "video_file",
                extensions: [],
                field_metadata: { description: "", rich_text_type: "standard" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "file",
                display_name: "Video Caption File",
                uid: "video_caption_file",
                extensions: [],
                field_metadata: { description: "", rich_text_type: "standard" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Stem",
                uid: "stem",
                field_metadata: {
                  allow_rich_text: true,
                  description: "",
                  multiline: false,
                  rich_text_type: "advanced",
                  options: [],
                  version: 3,
                },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Instruction",
                uid: "instruction",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "blocks",
                display_name: "Choices",
                blocks: [
                  {
                    title: "Choice",
                    uid: "choice",
                    schema: [
                      {
                        data_type: "boolean",
                        display_name: "Correct",
                        uid: "correct",
                        field_metadata: {
                          description: "",
                          default_value: false,
                        },
                        mandatory: false,
                        multiple: false,
                        non_localizable: false,
                        unique: false,
                      },
                      {
                        data_type: "number",
                        display_name: "Points",
                        uid: "points",
                        field_metadata: { description: "", default_value: "" },
                        mandatory: false,
                        multiple: false,
                        non_localizable: false,
                        unique: false,
                      },
                      {
                        data_type: "text",
                        display_name: "Body",
                        uid: "body",
                        field_metadata: {
                          allow_rich_text: true,
                          description: "",
                          multiline: false,
                          rich_text_type: "advanced",
                          options: [],
                          version: 3,
                        },
                        mandatory: false,
                        multiple: false,
                        non_localizable: false,
                        unique: false,
                      },
                      {
                        data_type: "text",
                        display_name: "Feedback",
                        uid: "feedback",
                        field_metadata: {
                          allow_rich_text: true,
                          description: "",
                          multiline: false,
                          rich_text_type: "advanced",
                          options: [],
                          version: 3,
                        },
                        mandatory: false,
                        multiple: false,
                        non_localizable: false,
                        unique: false,
                      },
                    ],
                  },
                ],
                multiple: true,
                uid: "choices",
                field_metadata: { instruction: "", description: "" },
                mandatory: false,
                non_localizable: false,
                unique: false,
              },
            ],
          },
          {
            title: "TFQuestion",
            uid: "tfquestion",
            schema: [
              {
                data_type: "text",
                display_name: "Prompt",
                uid: "prompt",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "file",
                display_name: "Video File",
                uid: "video_file",
                extensions: [],
                field_metadata: { description: "", rich_text_type: "standard" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "file",
                display_name: "Video Caption File",
                uid: "video_caption_file",
                extensions: [],
                field_metadata: { description: "", rich_text_type: "standard" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Stem",
                uid: "stem",
                field_metadata: {
                  allow_rich_text: true,
                  description: "",
                  multiline: false,
                  rich_text_type: "advanced",
                  options: [],
                  version: 3,
                },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Instruction",
                uid: "instruction",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Truthy Label",
                uid: "truthy_label",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Falsey Label",
                uid: "falsey_label",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "boolean",
                display_name: "Correct",
                uid: "correct",
                field_metadata: { description: "", default_value: false },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "number",
                display_name: "Points",
                uid: "points",
                field_metadata: { description: "", default_value: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Correct Feedback",
                uid: "correct_feedback",
                field_metadata: {
                  allow_rich_text: true,
                  description: "",
                  multiline: false,
                  rich_text_type: "advanced",
                  options: [],
                  version: 3,
                },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Incorrect Feedback",
                uid: "incorrect_feedback",
                field_metadata: {
                  allow_rich_text: true,
                  description: "",
                  multiline: false,
                  rich_text_type: "advanced",
                  options: [],
                  version: 3,
                },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
            ],
          },
          {
            title: "FillBlanksQuestion",
            uid: "fillblanksquestion",
            schema: [
              {
                data_type: "text",
                display_name: "Prompt",
                uid: "prompt",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Instruction",
                uid: "instruction",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Correct Feedback",
                uid: "correct_feedback",
                field_metadata: {
                  allow_rich_text: true,
                  description: "",
                  multiline: false,
                  rich_text_type: "advanced",
                  options: [],
                  version: 3,
                },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Incorrect Feedback",
                uid: "incorrect_feedback",
                field_metadata: {
                  allow_rich_text: true,
                  description: "",
                  multiline: false,
                  rich_text_type: "advanced",
                  options: [],
                  version: 3,
                },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Stem",
                uid: "stem",
                field_metadata: {
                  allow_rich_text: true,
                  description: "",
                  multiline: false,
                  rich_text_type: "advanced",
                  options: [],
                  version: 3,
                },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "blocks",
                display_name: "Draggable Words",
                blocks: [
                  {
                    title: "Draggable Word",
                    uid: "draggable_word",
                    schema: [
                      {
                        data_type: "text",
                        display_name: "Word",
                        uid: "word",
                        field_metadata: {
                          description: "",
                          default_value: "",
                          version: 3,
                        },
                        format: "",
                        error_messages: { format: "" },
                        mandatory: false,
                        multiple: false,
                        non_localizable: false,
                        unique: false,
                      },
                      {
                        data_type: "number",
                        display_name: "Order",
                        uid: "order",
                        field_metadata: { description: "", default_value: "" },
                        mandatory: false,
                        multiple: false,
                        non_localizable: false,
                        unique: false,
                      },
                    ],
                  },
                ],
                multiple: true,
                uid: "draggable_words",
                field_metadata: { instruction: "", description: "" },
                mandatory: false,
                non_localizable: false,
                unique: false,
              },
            ],
          },
          {
            title: "ReorderListQuestion",
            uid: "reorderlistquestion",
            schema: [
              {
                data_type: "text",
                display_name: "Prompt",
                uid: "prompt",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Stem",
                uid: "stem",
                field_metadata: {
                  allow_rich_text: true,
                  description: "",
                  multiline: false,
                  rich_text_type: "advanced",
                  options: [],
                  version: 3,
                },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Instruction",
                uid: "instruction",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Correct Feedback",
                uid: "correct_feedback",
                field_metadata: {
                  allow_rich_text: true,
                  description: "",
                  multiline: false,
                  rich_text_type: "advanced",
                  options: [],
                  version: 3,
                },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Incorrect Feedback",
                uid: "incorrect_feedback",
                field_metadata: {
                  allow_rich_text: true,
                  description: "",
                  multiline: false,
                  rich_text_type: "advanced",
                  options: [],
                  version: 3,
                },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "blocks",
                display_name: "List",
                blocks: [
                  {
                    title: "Item",
                    uid: "item",
                    schema: [
                      {
                        data_type: "text",
                        display_name: "Text",
                        uid: "text",
                        field_metadata: {
                          description: "",
                          default_value: "",
                          version: 3,
                        },
                        format: "",
                        error_messages: { format: "" },
                        mandatory: false,
                        multiple: false,
                        non_localizable: false,
                        unique: false,
                      },
                      {
                        data_type: "number",
                        display_name: "Order",
                        uid: "order",
                        field_metadata: { description: "", default_value: "" },
                        mandatory: false,
                        multiple: false,
                        non_localizable: false,
                        unique: false,
                      },
                    ],
                  },
                ],
                multiple: true,
                uid: "list",
                field_metadata: { instruction: "", description: "" },
                mandatory: false,
                non_localizable: false,
                unique: false,
              },
            ],
          },
          {
            title: "ReorderWordsQuestion",
            uid: "reorderwordsquestion",
            schema: [
              {
                data_type: "text",
                display_name: "Prompt",
                uid: "prompt",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Stem",
                uid: "stem",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Instruction",
                uid: "instruction",
                field_metadata: {
                  description: "",
                  default_value: "",
                  version: 3,
                },
                format: "",
                error_messages: { format: "" },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Correct Feedback",
                uid: "correct_feedback",
                field_metadata: {
                  allow_rich_text: true,
                  description: "",
                  multiline: false,
                  rich_text_type: "advanced",
                  options: [],
                  version: 3,
                },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
              {
                data_type: "text",
                display_name: "Incorrect Feedback",
                uid: "incorrect_feedback",
                field_metadata: {
                  allow_rich_text: true,
                  description: "",
                  multiline: false,
                  rich_text_type: "advanced",
                  options: [],
                  version: 3,
                },
                mandatory: false,
                multiple: false,
                non_localizable: false,
                unique: false,
              },
            ],
          },
        ],
        multiple: true,
        uid: "variants",
        field_metadata: { instruction: "", description: "" },
        mandatory: false,
        non_localizable: false,
        unique: false,
      },
      {
        data_type: "reference",
        display_name: "Topic",
        reference_to: ["taxon_bottom_up"],
        field_metadata: {
          ref_multiple: true,
          ref_multiple_content_types: true,
        },
        uid: "topic",
        mandatory: false,
        multiple: false,
        non_localizable: false,
        unique: false,
      },
      {
        data_type: "text",
        display_name: "Client List",
        display_type: "dropdown",
        enum: {
          advanced: false,
          choices: [
            { value: "schneider" },
            { value: "ing" },
            { value: "comcast" },
          ],
        },
        multiple: false,
        uid: "client_list",
        field_metadata: { description: "", default_value: "", version: 3 },
        mandatory: false,
        non_localizable: false,
        unique: false,
      },
    ],
    uid: "questionitem",
    DEFAULT_ACL: { others: { read: false, create: false }, users: [] },
    SYS_ACL: {
      others: {
        read: false,
        create: false,
        update: false,
        delete: false,
        sub_acl: {
          read: false,
          create: false,
          update: false,
          delete: false,
          publish: false,
        },
      },
      roles: [],
    },
    created_at: "2023-06-21T19:48:34.142Z",
    updated_at: "2023-06-22T16:00:21.789Z",
    inbuilt_class: false,
    abilities: {
      get_one_object: true,
      get_all_objects: true,
      create_object: true,
      update_object: true,
      delete_object: true,
      delete_all_objects: true,
    },
    last_activity: {},
    maintain_revisions: true,
    _version: 23,
  },
} as QuestionItem;
